New logic with classes
olivandesign/calc pull request #1
Opened 2019-01-28 20:01 UTC by olivandesign

2019-01-28 20:14 UTC, olivandesign commented on script.js
> +    this.digit = this.convertToDigit();
Это лишнее дерьмо осталось

2019-01-29 07:20 UTC, ghost requested changes

2019-01-29 07:20 UTC, anatoliy8493 commented on index.html
> +                    <button class="button digit" data-action="7">7</button>
почитай про бем, button digit это два блока получается, лучше сделать button__digit или button_digit

2019-01-29 07:20 UTC, anatoliy8493 commented on script.js
> +    this.a = result ? result : null;
result || null

2019-01-29 07:20 UTC, anatoliy8493 commented on script.js
> +    return this.result;
сраху return this[this.operator]()

2019-01-29 07:20 UTC, anatoliy8493 commented on script.js
> +    return (this.a && this.b && this.operator) ? true : false;
просто return !!this.a && !!this.b && !!this.operator

2019-01-29 07:20 UTC, anatoliy8493 commented on script.js
> +      return parseInt(this.value.join(''), 10);
без else мона тк есть  return

2019-01-29 07:20 UTC, anatoliy8493 commented on script.js
> +  if (target.classList.contains("digit")) {
лучше switch делать с такими вещами тк в условии одно выражение
switch (true){
  case target.classList.contains("digit"): ...
}

2019-01-29 07:24 UTC, olivandesign commented on script.js
> +    return this.result;
Мне нужно, чтобы резалт записывался в объект. Думаю вообще return тогда уберу

2019-01-29 07:26 UTC, olivandesign commented on script.js
> +      return parseInt(this.value.join(''), 10);
Так же читабельнее, не?

2019-01-29 08:09 UTC, merged